### ISSUE TITLE
Add Markdown support

### ISSUE THREAD

**Issue by paradox41** [auiWorks/amCoder#10]
Currently, all I see is white for Markdown files. I am willing to make a PR using regular Monokai as a reference. If you prefer to do it yourself, [here is an example](https://github.com/paradox41/material-color-scheme/blob/master/Material.tmTheme#L286-L470) of the Markdown scheme.

**Comment by aioutecism** [comment]
Hi, paradox41
A PR would be really helpful. Thanks.

BTW, I personally use MacDown for markdowns. You should give it a try.

**Comment by aioutecism** [comment]
Added in 2.1.0.
