### ISSUE TITLE
Add old color_scheme Low-Profile Gray

### ISSUE THREAD

**Issue by marcosrjjunior** [auiWorks/amCoder#13]
`"color_scheme": "Packages/Theme - amCoder/Monokai Low-Profile Gray.tmTheme",`

![amcoder-gray](https://cloud.githubusercontent.com/assets/5287262/10550923/244d1cba-7420-11e5-9e44-7ce28ab7113d.png)

![Sublime-Sample](https://copy.com/thumbs_public/1J7qEGDEMIb8ouJK/sublime.png?size=1024)

**Comment by RichardPinheiro** [comment]
:+1:

**Comment by aioutecism** [comment]
Added it back in 2.1.0.
I'll publish a new file for the new color-scheme soon.
