### ISSUE TITLE
Bring back the real Monokai theme

### ISSUE THREAD

**Issue by AndreasBackx** [auiWorks/amCoder#14]
I was disappointed to see the update in my Sublime Text. The beautiful Monokai theme and color scheme are gone which is what I loved about amCoder. Could the real Monokai theme be added again?

**Comment by langerhans** [comment]
Agreed, would like to see the that too :+1:

**Comment by Niels-NTG** [comment]
I too am not pleased with this change. Please bring the old colours back as an option or by reverting the whole thing.

**Comment by aioutecism** [comment]
Added it back in 2.1.0.
I'll publish a new file for the new color-scheme soon.

**Comment by AndreasBackx** [comment]
Would it be possible to have the option of the 2.0 version (bright Monokai and gray background) and the 1.x version (Original Monokai and the typical Monokai background)? The 2.0 version was a nice refresh, but it was sometimes hard on the eyes. I wouldn't do away with it because it had something going for it. So had the original AmCoder style: minimal and completely Monokai. It would be great to have the fresh and bright Monokai with the gray background like in 2.0 and the Monokai version from 1.0.

**Comment by aioutecism** [comment]
OK. I'm reopening this.

**Comment by aioutecism** [comment]
Classic monokai theme added in 2.2.0.
You should get the update in 1 hour.

**Comment by AndreasBackx** [comment]
Is it possible to write down the specifications of the amCoder theme if that is what you're gonna call it? This way others can implement it elsewhere.

**Comment by aioutecism** [comment]
@AndreasBackx I'm not quite understand what you mean by specifications. It's totally ok to send PR to this repo or fork it.
