### ISSUE TITLE
Bring back amCoder Gray

### ISSUE THREAD

**Issue by alextegelid** [auiWorks/amCoder#15]
I don't think the 2.0.0 release is very fair to the lot of us using the gray alternative of amCoder. It came kind of out of the blue and pretty much broke my entire visual setup of Sublime Text. I suggest you bring back amCoder Gray and leave it as deprecated at the least.

For those of you that wish to stay with amCoder Gray, I've manually reverted to d5e8a07 and it's working just fine.

**Comment by aioutecism** [comment]
Added it back in 2.1.0.

You should get the update in an hour.

**Comment by alextegelid** [comment]
Thanks, I really appreciate it!

**Comment by alextegelid** [comment]
I got the update, but I can't find the gray alternative in there...

Also I want to mention that I've been using your theme for the past six months and I've been super satisfied. It's a really nice theme 👍🏼

**Comment by aioutecism** [comment]
The only theme comes with this package is the gray one (named `amCoder`).
If you can't find it, try restart your Sublime.

I'm glad you like this theme :)

**Comment by alextegelid** [comment]
Oh yeah, now I see it. Thanks!
