### ISSUE TITLE
Orange selection option

### ISSUE THREAD

**Issue by tobia** [auiWorks/amCoder#17]
Hi, love this theme!

I'm using the non-classic version, because I like the increased contrast, but I missed the orange selection of vanilla Monokai Bright. It's particurarly useful when using multiple selections, to see at a glance what is selected.

So I copied over `amCoder.tmTheme` into an override folder `Packages/Theme - amCoder/` and put this in it:

    
    <key>selection</key>
    <string>#9D550F</string>
    <key>selectionForeground</key>
    <string>#fffff8</string>
    <key>inactiveSelection</key>
    <string>#383838</string>
    <key>inactiveSelectionForeground</key>
    <string>#6d6d6d</string>

As far as I know, that's the only difference between the vanilla Bright and non-bright variants. Maybe you could add it as a variant too?

**Comment by aioutecism** [comment]
Added bright version of `amCoder` and `amCoder Classic`.
The update should come in an hour.
