### ISSUE TITLE
"Open Files" vertical alignment

### ISSUE THREAD

**Issue by Francisc** [auiWorks/amCoder#21]
Hello,

Check out this screenshot of ST running on Windows:
![ss](https://cloud.githubusercontent.com/assets/699657/12279541/704f6ffe-b990-11e5-865b-f8c4a7bda2d0.jpg)

Would it be possible to increase the height of the "OPEN FILES" container so that it's as high as the tab bar?

**Comment by aioutecism** [comment]
It's not possible to change header row's height individually.

The options are:

1. Change `tab_height` in `Tab set`.
2. Change `row_padding` in `Sidebar tree`.

Both would affect other appearance so I can't make these change in master.

**Comment by Francisc** [comment]
That's kind of annoying of Sublime to not add that option.
Thank you for your quick reply.

**Comment by aioutecism** [comment]
You are welcome.
