### ISSUE TITLE
Light theme doesn't work

### ISSUE THREAD

**Issue by jonathanhirz** [auiWorks/amCoder#22]
Sublime Text 3 3114, Light theme just shows all black on sidebar, tabs, bottom bar, etc.

**Comment by jonathanhirz** [comment]
I installed this with git/clone into my Packages folder, and the light theme works. So maybe it just hasn't updated in Package Control yet =]

**Comment by aioutecism** [comment]
Yes, the light theme is somehow uncompleted. I haven't publish it to Package Control.
