### ISSUE TITLE
Sidebar icons

### ISSUE THREAD

**Issue by gj1118** [auiWorks/amCoder#8]
Hi , 
This is awesome. I absolutely love this . Is there a way you can add folder icons like Seti_UI/Cobalt2 does please ?  

Thanks

**Comment by Marcel-Robitaille** [comment]
Yes please add sidebar icons!

**Comment by aioutecism** [comment]
Sidebar icons are added in 2.0.0.
Enjoy!

**Comment by Marcel-Robitaille** [comment]
Awesome! Thanks!
